export const items = [
  {
    id: 1,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 2,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 3,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 4,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 5,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 6,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 7,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 8,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 9,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 10,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 11,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 12,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 13,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 14,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 15,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 16,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 17,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 18,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 19,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 20,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 21,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 22,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 23,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 24,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 25,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 26,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 27,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 28,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 29,
    title: 'Item 1',
    image: require('../../../assets/images/Logo_1.png'),
    description: 'This is the description for Item 1',
  },
  {
    id: 30,
    title: 'Item 1',
    image: require(`../../../assets/images/Logo_1.png`),
    description: 'This is the description for Item 1',
  },
];
